# dbr-managed — re-written by `dbr run`. Manual edits will be lost.
location /production/ {
    proxy_pass http://172.18.0.1:8068;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
