server {
    listen 80;
    server_name portal.open-reporting.dev;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name portal.open-reporting.dev;

    ssl_certificate     /etc/letsencrypt/live/open-reporting.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/open-reporting.dev/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'HIGH:!aNULL:!MD5';
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    root /usr/share/nginx/charts;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache chart HTML files for 1 hour
    location ~* \.html$ {
        add_header Cache-Control "public, max-age=3600";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    }
}
