#!/usr/bin/env python3
"""
Institution coverage matrix — the bridge between the layered ingestion strategy.

For every central institution in the KPP master registry, determines:
  - Layer 1 (dane.gov.pl): does it publish to the national portal? how many datasets?
  - Layer 2 (direct):      do we already have a direct source for it in our registry?
  - => GAP if neither.

Output:
  docs/institution-coverage-matrix.md  — per-institution status, the Layer-2 worklist

Inputs (produced by the two enumerators):
  data/kpp_institutions.json         — 132 central institutions (who exists)
  data/danegovpl_institutions.json   — dane.gov.pl publishers (who has data)
  products/ingestion/registry/source_registry.yaml — our 45 sources

Usage:
    python3 infra/scheduler/coverage_matrix.py
"""
import json
import logging
import re
import sys
from pathlib import Path

import yaml

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

REPO = Path("/opt/open-reporting")
KPP = REPO / "data/kpp_institutions.json"
DGP = REPO / "data/danegovpl_institutions.json"
REG = REPO / "products/ingestion/registry/source_registry.yaml"
OUT = REPO / "docs/institution-coverage-matrix.md"

_STOP = {"w", "i", "do", "spraw", "oraz", "the", "z", "na", "rzeczypospolitej",
         "polskiej", "polski", "rp"}


def norm(s: str) -> set[str]:
    s = (s or "").lower()
    s = re.sub(r"[^a-ząćęłńóśźż0-9 ]", " ", s)
    return {w for w in s.split() if len(w) > 2 and w not in _STOP}


# Institutions whose primary data is their OWN api (already covered directly,
# even though dane.gov.pl may also list them). Keyed by a distinctive token.
DIRECT_SOURCES = {
    "statystyczny": "GUS — bdl/dbw APIs",
    "narodowy bank": "NBP — api.nbp.pl (nbp_api)",
    "finansów": "MF — OpenBudget (mf_api)",
    "zdrowia": "NFZ — nfz_bulk (id=32)",
    "ubezpieczeń": "ZUS — zus_bulk (id=20)",
    "energetyki": "URE — ure_bulk (id=107)",
    "edukacji": "MEN — men_api (id=165)",
    "dróg krajowych": "GDDKiA — gddkia_bulk (id=55)",
    "ochrony środowiska": "GIOŚ — gios_bulk",
    "sprawiedliwości": "KRS / MS — krs_api (id=24)",
}


def main() -> int:
    central = json.loads(KPP.read_text())["institutions"]
    dgp = json.loads(DGP.read_text())["institutions"]
    reg = yaml.safe_load(REG.read_text())["sources"]

    # dane.gov.pl publisher index: token-set -> datasets
    dgp_idx = [(norm(d["title"]), d["title"], d["datasets"], d["id"]) for d in dgp]

    def dgp_match(name: str):
        toks = norm(name)
        best = None
        for dtoks, dtitle, dn, did in dgp_idx:
            if not dtoks:
                continue
            overlap = len(toks & dtoks)
            # strong match: most of the shorter name's tokens shared
            if overlap >= 2 and overlap >= min(len(toks), len(dtoks)) * 0.6:
                if best is None or dn > best[1]:
                    best = (dtitle, dn, did)
        return best

    def direct_match(name: str):
        nl = name.lower()
        for tok, label in DIRECT_SOURCES.items():
            if tok in nl:
                return label
        return None

    rows = []
    n_layer1 = n_layer2 = n_gap = 0
    for inst in central:
        name = inst["name"].title()
        www = inst["www"]
        direct = direct_match(inst["name"])
        dm = dgp_match(inst["name"])
        if direct:
            status, detail, n_layer2 = "DIRECT", direct, n_layer2 + 1
        elif dm:
            status, detail, n_layer1 = "dane.gov.pl", f"{dm[1]} datasets (id={dm[2]})", n_layer1 + 1
        else:
            status, detail, n_gap = "GAP", "no data source found yet", n_gap + 1
        rows.append((status, name, www, detail))

    # order: GAP first (worklist), then dane.gov.pl, then DIRECT
    order = {"GAP": 0, "dane.gov.pl": 1, "DIRECT": 2}
    rows.sort(key=lambda r: (order[r[0]], r[1]))

    lines = [
        "# Institution coverage matrix",
        "",
        "The bridge for the layered ingestion strategy. For each of the "
        f"**{len(central)} central institutions** (KPP master registry):",
        "",
        "- **DIRECT** — we already ingest it from its own API/bulk "
        f"({n_layer2} institutions)",
        f"- **dane.gov.pl** — Layer 1 covers it (publishes to the portal) "
        f"({n_layer1} institutions)",
        f"- **GAP** — no data source found yet; needs Layer-2 research "
        f"({n_gap} institutions)",
        "",
        "Auto-generated by `infra/scheduler/coverage_matrix.py`. Name-matched "
        "(fuzzy) — verify edge cases against the live portal.",
        "",
        "## Worklist — institutions to research (GAP first)",
        "",
        "| Status | Institution | Website | Detail |",
        "|---|---|---|---|",
    ]
    for status, name, www, detail in rows:
        badge = {"GAP": "🔴 GAP", "dane.gov.pl": "🟡 dane.gov.pl", "DIRECT": "🟢 DIRECT"}[status]
        link = f"[site](http://{www.replace('https://','').replace('http://','').rstrip('/')})" if www else "—"
        lines.append(f"| {badge} | {name} | {link} | {detail} |")
    lines.append("")
    OUT.write_text("\n".join(lines))
    log.info(f"coverage: DIRECT={n_layer2}, dane.gov.pl={n_layer1}, GAP={n_gap} → {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
