#!/usr/bin/env python3
"""
dane.gov.pl institution enumerator.

Pages through every institution on Poland's national open-data portal, records
its dataset/resource counts and type, cross-references against our source
registry, and writes a ranked candidate list. Turns "go through sources one by
one" into an automatically-generated, prioritised worklist.

Output:
  docs/danegovpl-institutions.md   — ranked human-readable report
  data/danegovpl_institutions.json — full machine-readable dump

Usage:
    python3 infra/scheduler/danegovpl_enumerator.py
    python3 infra/scheduler/danegovpl_enumerator.py --max-pages 5   # quick sample
"""
import argparse
import json
import logging
import sys
import time
from pathlib import Path

import requests
import yaml

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

REPO = Path("/opt/open-reporting")
API = "https://api.dane.gov.pl/1.4/institutions"
REGISTRY = REPO / "products/ingestion/registry/source_registry.yaml"
OUT_JSON = REPO / "data/danegovpl_institutions.json"
OUT_MD = REPO / "docs/danegovpl-institutions.md"
HEADERS = {"Accept": "application/json", "User-Agent": "OpenReporting-DataPipeline/1.0"}

# Institutions we already cover, keyed by their CORRECT dane.gov.pl id (verified
# 2026-06-14). NB: our original universal_bulk_downloader IDs were all WRONG —
# this map is the corrected reference.
COVERED_BY_ID = {
    "34": "GUS — own APIs (BDL/DBW); dane.gov.pl secondary",
    "32": "nfz_bulk (was wrongly id=31)",
    "20": "zus_bulk (was wrongly id=47)",
    "107": "ure_bulk (was wrongly id=58)",
    "165": "men_api (was wrongly id=15)",
    "55": "gddkia_bulk (was wrongly id=106)",
    "24": "krs_api / Min. Sprawiedliwości",
}
# Big institutions whose PRIMARY data is their own API — not dane.gov.pl.
PRIMARY_API = {"główny urząd statystyczny": "GUS BDL/DBW", "narodowy bank polski": "NBP API",
               "ministerstwo finansów": "MF OpenBudget"}
# Property-developer reporting registry — mandatory filings, not a data source.
NOISE_TYPES = {"developer"}


def fetch_all(max_pages: int | None) -> list[dict]:
    out, page = [], 1
    session = requests.Session()
    while True:
        r = session.get(API, params={"per_page": 100, "page": page}, headers=HEADERS, timeout=60)
        r.raise_for_status()
        body = r.json()
        data = body.get("data", [])
        if not data:
            break
        for it in data:
            a = it.get("attributes", {})
            rel = it.get("relationships", {})
            out.append({
                "id": it.get("id"),
                "title": a.get("title", ""),
                "abbreviation": a.get("abbreviation", ""),
                "type": a.get("institution_type", ""),
                "regon": a.get("regon", ""),
                "website": a.get("website", ""),
                "datasets": rel.get("datasets", {}).get("meta", {}).get("count", 0),
                "resources": rel.get("resources", {}).get("meta", {}).get("count", 0),
            })
        total = body.get("meta", {}).get("count", 0)
        log.info(f"page {page}: {len(out)}/{total} institutions")
        if len(out) >= total:
            break
        page += 1
        if max_pages and page > max_pages:
            break
        time.sleep(0.2)
    return out


def load_registry_keys() -> set[str]:
    reg = yaml.safe_load(REGISTRY.read_text())
    return {s["source_key"] for s in reg.get("sources", [])}


def main(max_pages: int | None) -> int:
    insts = fetch_all(max_pages)
    with_data = [i for i in insts if i["datasets"] > 0]
    # Public institutions only — exclude the property-developer reporting registry
    public = [i for i in with_data if i["type"] not in NOISE_TYPES]
    public.sort(key=lambda x: x["datasets"], reverse=True)

    OUT_JSON.write_text(json.dumps(
        {"total_institutions": len(insts), "with_data": len(with_data),
         "public_with_data": len(public), "institutions": public}, ensure_ascii=False, indent=2))

    from collections import Counter
    types = Counter(i["type"] for i in with_data)

    covered = [i for i in public if str(i["id"]) in COVERED_BY_ID]
    uncovered = [i for i in public if str(i["id"]) not in COVERED_BY_ID]

    def primary(i):
        for k, v in PRIMARY_API.items():
            if k in i["title"].lower():
                return v
        return None

    lines = [
        "# dane.gov.pl — institution enumeration & coverage",
        "",
        "Auto-generated by `infra/scheduler/danegovpl_enumerator.py`. The current",
        "inventory of every institution publishing open data on Poland's national",
        "portal — the master list for systematic source coverage.",
        "",
        f"- **{len(insts):,} institutions** total · **{len(with_data):,} publish data** · "
        f"**{len(public):,} are public** (excl. {types.get('developer',0)} property-developer filings)",
        f"- By type (with data): " + ", ".join(f"{t or '—'}={n}" for t, n in types.most_common()),
        f"- We already cover **{len(covered)}** of these by source registry; "
        f"**{len(uncovered)}** public publishers remain.",
        "",
        "## ⚠ Corrected institution IDs",
        "Our original `universal_bulk_downloader` IDs were all wrong (dane.gov.pl",
        "reassigned them). Correct, verified IDs:",
        "",
        "| Source | Wrong id (old) | Correct id | Datasets |",
        "|---|--:|--:|--:|",
        "| NFZ | 31 | **32** | 339 |",
        "| ZUS | 47 | **20** | 94 |",
        "| URE | 58 | **107** | 76 |",
        "| MEN | 15 | **165** | 35 |",
        "| GDDKiA | 106 | **55** | 6 |",
        "",
        "## Where NBP / KRS / NIK / ZUS belong (all category b — institutional)",
        "- **NBP** — NOT on dane.gov.pl → own API (covered: `nbp_api`).",
        "- **KRS** — the register is via Min. Sprawiedliwości (id=24, 81 ds on dane.gov.pl) "
        "+ the KRS lookup API (covered: `krs_api`).",
        "- **NIK** (Najwyższa Izba Kontroli) — NOT on dane.gov.pl → needs nik.gov.pl as a NEW source.",
        "- **ZUS** — id=20 on dane.gov.pl (94 ds) + own statistics portal (covered: `zus_bulk`).",
        "",
        "## Top 50 PUBLIC publishers not yet covered (the worklist)",
        "",
        "| # | Datasets | Type | Institution | id | Note |",
        "|--:|--:|---|---|--:|---|",
    ]
    for rank, i in enumerate(uncovered[:50], 1):
        p = primary(i)
        note = f"own API: {p}" if p else ""
        lines.append(f"| {rank} | {i['datasets']:,} | {i['type']} | {i['title'][:50]} | {i['id']} | {note} |")
    lines += [
        "",
        "## How to read this",
        "- Big national institutions (GUS, NBP, MF) publish richer data via their **own APIs** — keep those.",
        "- dane.gov.pl is best for the **mid-tier & long-tail** public institutions with no API of their own.",
        "- Work down the worklist to expand coverage. Full dump: `data/danegovpl_institutions.json`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines))
    log.info(f"{len(insts)} total, {len(public)} public-with-data, {len(uncovered)} uncovered → {OUT_MD}")
    return 0


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--max-pages", type=int, default=None)
    args = p.parse_args()
    sys.exit(main(args.max_pages))
