#!/usr/bin/env python3
"""
Generate the complete ingestion schedule for all wired sources.

Assigns every source in the registry a cadence + staggered window + invocation,
based on its extractor engine and ingestion mode. Writes
products/ingestion/registry/ingestion_schedule.yaml (consumed by the orchestrator
run_ingestion.py and the admin-portal plan generator).

Cadence policy (by engine):
  continuous  bdl/dbw            — budget-paced, run by run_gus_bulk.sh cron (not orchestrated here)
  nightly     incremental, uzp   — fast-moving (FX, procurement)
  weekly      APIs, institutions, datasets, intl, harvester, pl_api
  monthly     bulk, WFS spatial, web-scraper reports, kpp

Staggering: each source gets a deterministic minute offset so a cadence run
spreads load rather than firing everything at once.

Usage: python3 infra/scheduler/generate_schedule.py
"""
import logging
import sys
from pathlib import Path

import yaml

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

REPO = Path("/opt/open-reporting")
REGISTRY = REPO / "products/ingestion/registry/source_registry.yaml"
OUT = REPO / "products/ingestion/registry/ingestion_schedule.yaml"

# engine basename → (cadence, base window UTC hour)
ENGINE_CADENCE = {
    "bdl_extractor.py":                  ("continuous", None),
    "dbw_extractor.py":                  ("continuous", None),
    "run_incremental.py":                ("nightly", 22),
    "uzp_extractor.py":                  ("nightly", 1),
    "intl_extractor.py":                 ("weekly", 5),
    "pl_api_extractor.py":               ("weekly", 2),
    "danegovpl_harvester.py":            ("weekly", 6),
    "danegovpl_institution_extractor.py": ("weekly", 3),
    "danegovpl_dataset_extractor.py":    ("weekly", 4),
    "wfs_extractor.py":                  ("monthly", 7),
    "web_scraper_extractor.py":          ("monthly", 8),
    "run_bulk.py":                       ("monthly", 0),
    "universal_bulk_downloader.py":      ("monthly", 0),
    "kpp_institution_registry.py":       ("monthly", 6),
    "mf_extractor.py":                   ("disabled", None),
}
PRIORITY = {"continuous": 1, "nightly": 1, "weekly": 2, "monthly": 3, "disabled": 9}


def main() -> int:
    reg = yaml.safe_load(REGISTRY.read_text())["sources"]
    entries = []
    stagger = {}  # cadence -> running minute offset
    for s in sorted(reg, key=lambda x: x["source_key"]):
        if s.get("default_status") in ("skipped", "blocked"):
            continue
        path = s.get("extractor_path")
        if not path:
            continue
        eng = path.split("/")[-1]
        cadence, hour = ENGINE_CADENCE.get(eng, ("monthly", 9))
        if cadence == "disabled":
            continue
        if cadence == "continuous":
            window = "continuous (run_gus_bulk.sh 03:30 / 04:00+16:00 UTC)"
        else:
            off = stagger.get(cadence, 0)
            stagger[cadence] = off + 3
            mins = off % 60
            hh = (hour + off // 60) % 24
            day = " Mon" if cadence == "weekly" else (" 1st" if cadence == "monthly" else "")
            window = f"{hh:02d}:{mins:02d} UTC{day}"
        entries.append({
            "source_key": s["source_key"],
            "cadence": cadence,
            "window": window,
            "engine": eng,
            "mechanism": f"orchestrator: run_ingestion.py --cadence {cadence}",
            "priority": PRIORITY[cadence],
            "notes": s.get("scope", "")[:80] if s.get("scope") else None,
        })
    OUT.write_text(
        "# AUTO-GENERATED by infra/scheduler/generate_schedule.py — do not hand-edit.\n"
        "# Complete cadence/window/engine schedule for every wired source.\n"
        + yaml.dump({"version": 2, "entries": entries}, allow_unicode=True,
                    default_flow_style=False, sort_keys=False, width=200)
    )
    from collections import Counter
    c = Counter(e["cadence"] for e in entries)
    log.info(f"schedule: {len(entries)} entries — {dict(c)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
