#!/usr/bin/env python3
"""
KPP — Katalog Podmiotów Publicznych — master institution registry.

Downloads the latest monthly KPP export from dane.gov.pl (dataset 3520) — the
authoritative catalogue of every Polish public entity (~87k: ministries,
central offices, inspectorates, agencies, courts, schools, hospitals, local
governments) — and produces a structured master list for source coverage.

Unlike the dane.gov.pl publisher enumeration, this lists ALL institutions
whether or not they publish open data — so nothing (e.g. NIK, NBP) is missed.

Output:
  docs/poland-institutions-master.md   — central institutions + type breakdown
  data/kpp_institutions.json           — full machine-readable central-institution list

Usage:
    python3 infra/scheduler/kpp_institution_registry.py
"""
import json
import logging
import sys
from collections import Counter
from pathlib import Path

import openpyxl
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

REPO = Path("/opt/open-reporting")
DATASET_API = "https://api.dane.gov.pl/1.4/datasets/3520/resources?per_page=40"
RES_FILE = "https://api.dane.gov.pl/resources/{id}/file"
OUT_JSON = REPO / "data/kpp_institutions.json"
OUT_MD = REPO / "docs/poland-institutions-master.md"
TMP = Path("/tmp/kpp_latest.xlsx")
HEADERS = {"Accept": "application/json", "User-Agent": "OpenReporting-DataPipeline/1.0"}

# National-level types worth checking for data (vs the school/kindergarten long tail)
HIGH_VALUE_TYPES = {
    "instytucje centralne", "jednostki Krajowej Administracji Skarbowej",
    "jednostki Policji", "sądy", "prokuratury", "urzędy wojewódzkie",
    "regionalne izby obrachunkowe", "samorządowe kolegia odwoławcze",
}


def latest_resource_id() -> str:
    r = requests.get(DATASET_API, headers=HEADERS, timeout=60)
    r.raise_for_status()
    res = [(x["id"], x["attributes"].get("created", ""), x["attributes"].get("format"))
           for x in r.json()["data"]]
    res = [x for x in res if x[2] == "xlsx"]
    res.sort(key=lambda x: x[1] or "", reverse=True)
    log.info(f"latest KPP resource: id={res[0][0]} created={res[0][1]}")
    return res[0][0]


def download(rid: str) -> None:
    with requests.get(RES_FILE.format(id=rid), headers=HEADERS, timeout=180, stream=True) as r:
        r.raise_for_status()
        with open(TMP, "wb") as f:
            for chunk in r.iter_content(65536):
                f.write(chunk)
    log.info(f"downloaded {TMP.stat().st_size:,} bytes")


def main() -> int:
    download(latest_resource_id())
    wb = openpyxl.load_workbook(TMP, read_only=True)
    ws = wb.active
    it = ws.iter_rows(values_only=True)
    header = list(next(it))
    idx = {h: i for i, h in enumerate(header)}
    ti, ni, wi = idx["Typ podmiotu"], idx["Nazwa podmiotu"], idx["Strona www"]
    kati, regi, krsi = idx["Kategoria podmiotu"], idx["REGON"], idx["KRS"]

    typ = Counter()
    central = []
    total = 0
    for r in it:
        total += 1
        typ[r[ti]] += 1
        if r[ti] == "instytucje centralne" and r[kati] == "PUBLIC":
            central.append({"name": r[ni], "www": (r[wi] or "").strip(),
                            "regon": r[regi], "krs": r[krsi]})
    wb.close()

    # de-dup by name
    seen, uniq = set(), []
    for c in sorted(central, key=lambda x: x["name"] or ""):
        if c["name"] not in seen:
            seen.add(c["name"])
            uniq.append(c)

    OUT_JSON.write_text(json.dumps(
        {"total_entities": total, "central_institutions": len(uniq),
         "type_breakdown": dict(typ.most_common()), "institutions": uniq},
        ensure_ascii=False, indent=2))

    lines = [
        "# Poland — master public-institution registry (KPP)",
        "",
        "Source: **Katalog Podmiotów Publicznych** (dataset 3520 on dane.gov.pl),",
        "the official catalogue of every Polish public entity. Refreshed monthly.",
        "Auto-generated by `infra/scheduler/kpp_institution_registry.py`.",
        "",
        "This lists ALL institutions — whether or not they publish open data — so",
        "nothing is missed. It is the *who exists* master list; pair it with the",
        "dane.gov.pl publisher enumeration (`danegovpl-institutions.md`) for *who has data*.",
        "",
        f"- **{total:,} public entities** total",
        f"- **{len(uniq)} central institutions** (`instytucje centralne`) — the national bodies",
        "",
        "## Entity types (top 30 — shows the long tail)",
        "",
        "| Count | Type |",
        "|--:|---|",
    ]
    for t, n in typ.most_common(30):
        lines.append(f"| {n:,} | {t} |")
    lines += [
        "",
        "## All central institutions (the source-coverage worklist)",
        "",
        "Every national public body. Check each for a data source (own API, "
        "dane.gov.pl, or bulk files).",
        "",
        "| Institution | Website |",
        "|---|---|",
    ]
    for c in uniq:
        www = c["www"]
        link = f"[{www}](http://{www.replace('https://','').replace('http://','')})" if www else ""
        lines.append(f"| {c['name'].title()} | {link} |")
    lines.append("")
    OUT_MD.write_text("\n".join(lines))
    log.info(f"{total} entities, {len(uniq)} central institutions → {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
